name: Scala

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - jdk8
          - jdk11
          - jdk17
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Starting test dependencies"
        run: docker-compose up -d

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12

      # - name: "Install Cachix ❄️"
      #   uses: cachix/cachix-action@v8
      #   with:
      #     name: tele-kinesis
      #     signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Run with ${{ matrix.java }} 🚀"
        run: nix-shell --argstr jdk "${{ matrix.java }}" --run "sbt compile" nix/ci.nix
