name: Scala

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - jdk8
          - jdk11
          - jdk17
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          ref: ${{ github.head_ref }}

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12

      - name: "Run with ${{ matrix.java }} 🚀"
        run: nix-shell --run "sbt docs/mdoc" nix/ci.nix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated documentation
          file_pattern: README.md
